config/routes.rb
MyWeb::Application.routes.draw do
  root :to => "main#index", :as => 'root'
  match "/" => "main#index"
  match "/naves" => "main#naves"
  match 'brands' => 'brand#get_all', :as => 'json'
  match 'string' => 'brand#string', :as => 'string'
  match 'validate_login' => 'car_user#validate_login', :as => 'json'

  match '/:locale/about-me' => 'main#about_me', :as => 'about_me'
  match '/about-me' => 'main#about_me', :as => 'about_me'

  match '/:locale/guides/:category_path' => 'main#article_list', :as => 'guides'
  match '/:locale/guides/:category_path/:article_path' => 'main#article_content', :as => 'guides_category_and_article'

  match '/auth/:provider/callback', to: 'authorization#callback'

  match '/:locale/demos/:article_path' => 'main#demo_content', :as => 'demo_content'  

  match 'comment/create' => 'comment#create', :via => 'post', :as => 'create_comment'
  match 'comment/delete/:id' => 'comment#delete', :as => 'delete_comment'
  match 'change_language/:locale' => 'main#change_language', :as => 'change_language'

  match 'rating/change_rating' => 'rating#change_rating', :as => 'change_rating'

  match 'chat/post_message' => 'chat#post_message', :as => 'post_message'
  match 'chat/typing_status' => 'chat#typing_status', :as => 'typing_status'
  match 'chat/change_nickname' => 'chat#change_nickname', :as => 'change_nickname'

  match 'show/socialnetworks' => 'main#show_socialnetworks_popup', :as => 'socialnetworks'

  match "/:locale/cv" => "main#download_cv"
  match "/cv" => "main#download_cv"

  match "/signout" => "sessions#destroy", :as => :signout
  match "/:locale" => "main#index"


  












end

app/controllers/main_controller.rb
require 'set'
require 'pusher'

class MainController < ApplicationController

  def index  
    articles = Article.get_articles_for_dashboard(@locale)
    
    @random_articles = []
    random_array = get_random_array(40, articles.size)

    random_array.each do |index|
      @random_articles << articles[index]
    end

    @pages_path = []
    @pages_path << [ 'Dashboard', '/' ]
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def article_list  
    @pages_path = []
    @pages_path << ['Dashboard', '/' ]
    @pages_path << [@category_selected.name, @category_selected.path]
    
    # Getting a list of articles
    @articles = Article.get_articles_by_category_id(@category_selected.id, @locale)

    @articles.each do |c|
      logger.debug c.messages
    end

    respond_to do |format|
      format.html # article_list.html.erb
    end
  end

  def article_content

    @article_selected  = Article.find_by_path_and_language(params[:article_path], @locale) 
    @article_selected.content = get_file_as_string(Rails.root.to_s + @article_selected.route)

    # increment the visits
    @article_selected.visits += 1

    # save the article
    @article_selected.save

    @pages_path = []
    @pages_path << [ 'Dashboard', '/' ]
    @pages_path << [ @category_selected.name, @category_selected.path ]
    @pages_path << [ @article_selected.name, @article_selected.path ]

    session[:current_url] = "#{request.protocol}#{request.host_with_port}#{request.fullpath}"

    respond_to do |format|
      format.html 
    end
  end

  def demo_content
    @article_selected  = Article.find_by_path_and_language(params[:article_path], @locale) 
    @category_selected.id = Constants::CATEGORY_DEMO_ID
    @category_selected.path = ''

    @article_selected.content = get_file_as_string(Rails.root.to_s + @article_selected.route)

    # increment the visits
    @article_selected.visits += 1

    # save the article
    @article_selected.save

    @pages_path = []
    @pages_path << [ 'Dashboard', '/' ]
    @pages_path << [ @article_selected.name, @article_selected.path ]

    session[:current_url] = "#{request.protocol}#{request.host_with_port}#{request.fullpath}"

    respond_to do |format|
      format.html { render 'main/article_content' }
    end
  end

  def create_comment

    @article  = Article.find_by_path(params[:article_path]) 

    comment = Comment.new
    comment.name = params[:name]
    comment.email = params[:email]
    comment.website = params[:website]
    comment.description = params[:comments]
    comment.created_at = Time.new
    comment.updated_at = Time.new
    comment.article_id = @article.id

    if params[:name].nil? or params[:name] == '' then
      @name_error = 'Enter a name bestia'
    elsif params[:comments].nil? or params[:comments] == '' then

    else
      # save comment
      comment.save

      # save article
      @article.update_attributes(messages: @article.messages+1)
      
      @article.content = get_file_as_string(Rails.root.to_s + @article.route)
    end

    #CommentMailer.comment_alert_message(comment, @article, @category).deliver

    respond_to do |format|
      format.html {redirect_to guides_category_and_article_url(@locale, @category_selected.path, @article.path), :jeje => 'caca'}
    end
   
  end

  def show_socialnetworks_popup
    render 'popups/socialnetworks', :layout => false
  end
   
  def get_file_as_string(filename)
    data = ''
    f = File.open(filename, "r") 
    f.each_line { |line| data += line }
    return data
  end

  def get_random_array(n, max)
    randoms = Set.new
    loop do
      randoms << rand(max)
      return randoms.to_a if randoms.size >= n
    end
  end

  def about_me
    @pages_path = Array.new
    
    @about_me = get_file_as_string(Rails.root.to_s + '/app/guides/' + @locale + '/others/about_me.txt')
    respond_to do |format|
      format.html
    end
  end

  def download_cv
    send_file(Rails.root.to_s + '/files/' + @locale + '/CV.pdf', :filename => 'carlos-duclos-cv.pdf', :disposition => 'inline', :type => "application/pdf")
  end

  def change_language
    if request.referer.include? ('/' + Constants::LANG_ENGLISH + '/')
      current_locale = Constants::LANG_ENGLISH
    end

    if request.referer.include? ('/' + Constants::LANG_SPANISH + '/')
      current_locale = Constants::LANG_SPANISH
    end

    I18n.locale = params[:locale]

    logger.debug current_locale
    logger.debug params[:locale]
    logger.debug request.referer

    if current_locale.nil?
      # add the locale to the url, next to the domain
      redirect_to "#{request.protocol}#{request.host_with_port}" + '/' + params[:locale]
    else
      # replace the new locale
      redirect_to request.referer.sub!('/' + current_locale + '/', '/' + params[:locale] + '/')
    end
    
  end

  def naves
    render 'main/naves', :layout => false
  end

end

app/views/main/about_me.html.erb
<%= markdown @about_me %>

app/views/main/article_content.html.erb
<!-- ARTICLES HEADER -->
<div class="articles-header">

  <!-- IMAGE -->
  <div class="image">
    <%= image_tag @article_selected.image_url, :size => '50x50' %>
  </div>

  <div class="description">

    <!-- TITLE -->
    <div class="description-title"><%= @article_selected.name %></div>

    <!-- INTRO -->
    <div class="description-intro"><%= @article_selected.small_description %></div>

  </div>
  <% path = ('demos'  + '/' + @article_selected.path) if @category_selected.id == Constants::CATEGORY_DEMO_ID %>
  <% path = ('guides' + '/' + @category_selected.path + '/' + @article_selected.path) if @category_selected.id != Constants::CATEGORY_DEMO_ID %>

  <div class="right-buttons">
    <%= render :partial => 'socialnetworks/facebook_button', :locals => {:url => root_url + path} %>
    <%= render :partial => 'socialnetworks/twitter_button', :locals => {:url => root_url + path} %>
    <% #render :partial => 'socialnetworks/googleplus_button', :locals => {:url => 'http://carlos21.com'} %>
  </div>

</div>

<!-- CONTENT -->
<div class="article-content">
  <%= markdown @article_selected.content %>
</div>

<div class="comments">
  
  <!-- COMMENTS LIST -->
  <%= render partial: 'comment/list', locals: {comments: @article_selected.comments} %>
  
  <!-- COMMENT FORM -->
  <%= render partial: 'comment/form' %>
  
  <div style="height:40px;"></div>
</div>

app/views/main/article_list.html.erb
<div class="articles-header">
  <div class="image">
    <%= image_tag @category_selected.image_url, :size => '50x50' %>
  </div>
  <div class="description">
    <div class="description-title"><%= @category_selected.name %></div>
    <div class="description-intro"><%= @category_selected.small_description %></div>
  </div>
</div>

<% @articles.each do |a| %>
  <div class="article">
    <div class="icon">
      <i class="icon-leaf"></i>
    </div>
    <%= link_to guides_category_and_article_path(@locale, @category_selected.path, a.path), :style =>'text-decoration: none;' do %>
      <div class="name"><%= a.name %></div>
      <div class="extra-info">
        <div><%= t(:messages_label)%> <%= a.messages %></div>
        <div><%= t(:visits_label)%> <%= a.visits %></div>
        <div><%= t(:last_update_label)%> <%= a.updated_at.to_s(:long) %></div>
      </div>
    <%  end %>
  </div>
<% end %>

  

app/views/main/index.html.erb
<!-- LOADING -->
<div id="loading">
  <img src="assets/loading.gif">
</div>

<!-- LUCK BUTTON -->
<div class="tryluck">
  <div id="we"></div>
  <input type="button" class="btn btn-inverse" style="font-size: 11px" value="Quick start" onclick="randomitem()" />
</div>

<!-- DASHBOARD -->
<% @random_articles.each do |a|%>
  <% days = (Time.now - a.created_at)/60/60/24 %>
  <div id="article_<%=a.id%>" class="random-item" style="overflow: hidden;">
    <%= link_to guides_category_and_article_path(@locale || I18n.locale, a.category.path, a.path) do %>
    <div class="random-item-image">
      <%= image_tag a.image_url, :size => '46x46' %>
    </div>
    <div class="random-item-name">
      <%= a.name %>
    </div>
    <!--<div class="random-item-description"></div>-->
    <% end %>

    <% if days < 7 %>
      <div class="corner">
        New
      </div>
    <% end %>
  </div>
<% end %>

app/views/main/naves.html.erb
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Juego de naves</title>
<%= javascript_include_tag "naves/mootools-core-1.4.5-full-compat-yc.js" %>
<%= javascript_include_tag "naves/mootools-more-1.4.0.1.js" %>
<%= javascript_include_tag "naves/kinetic-v4.3.3.min.js" %>
<%= javascript_include_tag "naves/spaceship.js" %>
<style>
  #container {
    margin: auto;
    width: 400px;
    height: 400px;
  }
  canvas {
    border: 1px solid #c3c3c3;
    background-color: #000;
  }
</style>
</head>
<body>

  <div id="container"></div>

</body>
</html>