config/routes.rb
MyWeb::Application.routes.draw do
  root :to => "main#index", :as => 'root'
  match "/" => "main#index"
  match "/naves" => "main#naves"
  match 'brands' => 'brand#get_all', :as => 'json'
  match 'string' => 'brand#string', :as => 'string'
  match 'validate_login' => 'car_user#validate_login', :as => 'json'

  match '/:locale/about-me' => 'main#about_me', :as => 'about_me'
  match '/about-me' => 'main#about_me', :as => 'about_me'

  match '/:locale/guides/:category_path' => 'main#article_list', :as => 'guides'
  match '/:locale/guides/:category_path/:article_path' => 'main#article_content', :as => 'guides_category_and_article'

  match '/auth/:provider/callback', to: 'authorization#callback'

  match '/:locale/demos/:article_path' => 'main#demo_content', :as => 'demo_content'  

  match 'comment/create' => 'comment#create', :via => 'post', :as => 'create_comment'
  match 'comment/delete/:id' => 'comment#delete', :as => 'delete_comment'
  match 'change_language/:locale' => 'main#change_language', :as => 'change_language'

  match 'rating/change_rating' => 'rating#change_rating', :as => 'change_rating'

  match 'chat/post_message' => 'chat#post_message', :as => 'post_message'
  match 'chat/typing_status' => 'chat#typing_status', :as => 'typing_status'
  match 'chat/change_nickname' => 'chat#change_nickname', :as => 'change_nickname'

  match 'show/socialnetworks' => 'main#show_socialnetworks_popup', :as => 'socialnetworks'

  match "/:locale/cv" => "main#download_cv"
  match "/cv" => "main#download_cv"

  match "/signout" => "sessions#destroy", :as => :signout
  match "/:locale" => "main#index"


  












end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :email, :name, :website, :photo_url, :article_id

  belongs_to :article
  belongs_to :demo
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def create

    if (session[:social_user].present?) 
      # is logged
      @article  = Article.find_by_path(params[:article_path]) 
      @category = Category.find(@article.category_id)
      articles = Article.get_articles_by_path(params[:article_path])
      social_user = session[:social_user]

      articles.each do |a|
        @comment = Comment.new
        @comment.name = social_user.name
        @comment.email = social_user.email
        @comment.photo_url = social_user.photo_url
        @comment.website = params[:website]
        @comment.description = params[:comments]
        @comment.created_at = Time.new
        @comment.updated_at = Time.new
        @comment.article_id = a.id

        # save comment
        @comment.save

        # save article
        a.update_attributes(messages: a.messages + 1)
      end

      render 'comment/_item', :layout => false, :status => 200
    else
      @form_title = t(:your_session_has_expired_label)
      # no logged // show popup
      render 'socialnetworks/_ask_for_login', :layout => false, :status => 202
    end
    
    #CommentMailer.comment_alert_message(comment, @article, @category).deliver

  end

  def delete
    comment = Comment.find(params[:id])
    comment.destroy
    @comment_id = params[:id]

    respond_to do |format|
      format.js
    end
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comment/_add_item.js.erb
$("comments-list").append("<%= escape_javascript(render :partial => 'comment/item', :locals => {:comment => @comment} )%>");

app/views/comment/_form.html.erb
<div id="modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-body">
    
  </div>
</div>

<div class="comments-form">
  <% if session[:social_user].present? %>

    <!-- COMMENT FORM -->
    <%= form_tag '/comment/create', id: 'form_comment' do %>
      <h3><%= t(:leave_a_comment_label) %></h3>
      <fieldset>

        <!-- NAME -->
        <!--<div class="control-group">
          <label class="control-label" for="name"><%= t(:name_label) %></label>
          <div class="input-prepend">
            <span class="add-on">
              <i class="icon-user" style="margin-top:1px"></i>
            </span>
            <%= text_field_tag :name, '', :class => 'input-xlarge', :placeholder => t(:enter_your_name_placeholder) %>
            <% if !@name_error.nil? then %>
            <%= @jeje %>
            <% end  %>

          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="email"><%= t(:email_label) %></label>
          <div class="input-prepend">
            <span class="add-on">@</span>
            <%= text_field_tag :email, '', :class => 'input-xlarge', :placeholder => t(:enter_your_email_placeholder) %>
          </div>
        </div>

        <!-- WEBSITE
        <div class="control-group">
          <label class="control-label" for="website"><%= t(:website_label) %></label>
          <div class="input-prepend">
            <span class="add-on">
              <i class="icon-globe" style="margin-top:2px"></i>
            </span>
            <%= text_field_tag :website, '', :class => 'input-xlarge', :placeholder => t(:enter_your_website_placeholder) %>
          </div>
        </div>-->

        <!-- COMMENTS -->
        <div class="control-group">
          <label class="control-label" for="comments"><%= t(:comments_label) %></label>
          <div class="controls">
            <%= text_area_tag :comments, '', :style => 'width: 299px; height: 80px;', :placeholder => t(:enter_your_comments_placeholder) %>
          </div>  
        </div>

        <%= hidden_field_tag 'article_path', 'article_path', :value => @article_selected.path %>
        <%= submit_tag t(:submit_button), :class => 'btn btn-info' %>
        
      </fieldset>
    <% end %>
  <% else %>
    <%= render :partial => 'socialnetworks/ask_for_login', :locals => {:@form_title => @form_title} %>
  <% end %>

  
</div>

app/views/comment/_item.html.erb
<!-- COMMENT -->
<div class="item" data-id="<%= @comment.id %>">

  <!-- IMAGE -->
  <div class="image">
    <%= image_tag @comment.photo_url, :class => 'userimage', :onerror => "this.src='" + root_url + '/assets/user-image.png' +"'" %>
  </div>

  <div class="description">

    <!-- TITLE -->
    <div class="description-title">
      <b><%= @comment.name %></b> 
      says:

    </div>

    <!-- CONTENT -->
    <div class="description-content">
      <%= @comment.description %>
    </div>

  </div>

  <%if session[:social_user].present? 
      if session[:social_user].uid == Constants::MY_FACEBOOK_UID %>
        <%= link_to 'x', delete_comment_path(@comment.id), :class => 'close-item', 'data-id' => @comment.id, :remote => true %>
  <%  end
    end %>
</div>

app/views/comment/_list.html.erb
<div class="comments-list">
  <% if comments.any? %>
    <h3><%= t(:comments_title) %></h3>
    <% comments.each do |c| %>
      <%= render :partial => 'comment/item', :locals => {:@comment => c} %>
    <% end %>
  <% end %>
</div>

app/views/comment/delete.js.erb
$('.comments-list .item[data-id="<%= @comment_id %>"]').fadeOut('slow')