config/routes.rb
MyWeb::Application.routes.draw do
  root :to => "main#index", :as => 'root'
  match "/" => "main#index"
  match "/naves" => "main#naves"
  match 'brands' => 'brand#get_all', :as => 'json'
  match 'string' => 'brand#string', :as => 'string'
  match 'validate_login' => 'car_user#validate_login', :as => 'json'

  match '/:locale/about-me' => 'main#about_me', :as => 'about_me'
  match '/about-me' => 'main#about_me', :as => 'about_me'

  match '/:locale/guides/:category_path' => 'main#article_list', :as => 'guides'
  match '/:locale/guides/:category_path/:article_path' => 'main#article_content', :as => 'guides_category_and_article'

  match '/auth/:provider/callback', to: 'authorization#callback'

  match '/:locale/demos/:article_path' => 'main#demo_content', :as => 'demo_content'  

  match 'comment/create' => 'comment#create', :via => 'post', :as => 'create_comment'
  match 'comment/delete/:id' => 'comment#delete', :as => 'delete_comment'
  match 'change_language/:locale' => 'main#change_language', :as => 'change_language'

  match 'rating/change_rating' => 'rating#change_rating', :as => 'change_rating'

  match 'chat/post_message' => 'chat#post_message', :as => 'post_message'
  match 'chat/typing_status' => 'chat#typing_status', :as => 'typing_status'
  match 'chat/change_nickname' => 'chat#change_nickname', :as => 'change_nickname'

  match 'show/socialnetworks' => 'main#show_socialnetworks_popup', :as => 'socialnetworks'

  match "/:locale/cv" => "main#download_cv"
  match "/cv" => "main#download_cv"

  match "/signout" => "sessions#destroy", :as => :signout
  match "/:locale" => "main#index"


  












end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :category_id, :name, :small_description, :content, :path, :route, :language, :visits, :messages, :image_url
  attr_accessor :content

  belongs_to :category
  has_many :comments

  def self.get_articles_for_dashboard(lang)
    self.includes(:category).where('language = ? and category_id != ?', lang, 10)
  end

  def self.get_article_by_path(path_filter, lang_filter)
    articles = where(path: path_filter, language: lang_filter)
    return articles[0] if articles.any?
  end

  def self.get_articles_by_category_id(category_id, lang_filter)
    articles = Article.select("articles.*")
                      .where("articles.category_id = ? and articles.language = ?", category_id, lang_filter)
                      .order('articles.created_at desc')

    #articles = Article.select("articles.*, count(c.id) as messages")
    #                  .joins('left join comments c on c.article_id = articles.id')
    #                  .where("articles.category_id = #{category_id} and articles.language = '#{lang_filter}'")
    #                  .order('articles.name asc')
    #                  .group("articles.id, articles.name, articles.small_description, articles.path, articles.route, articles.language, articles.visits, articles.image_url, articles.category_id")

    #articles = Article.all(:select => "articles.*, count(c.id) as messages_count",
    #                       :joins => 'left join comments c on c.article_id = articles.id',
    #                       :group => "articles.id, articles.name, articles.small_description, articles.path, articles.route, articles.language, articles.visits, articles.image_url, articles.category_id",
    #                       :order => 'articles.name asc'
    #                      ).where("articles.category_id = #{category_id} and articles.language = '#{lang_filter}'")
    return articles
  end

  def self.get_articles_by_path(path)
    where(path: path)
  end
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid

  def self.create_with_omniauth(auth)
    create! do |authorization|
      authorization.provider = auth.provider
      authorization.uid = auth.uid
    end
  end

  def self.find_by_provider_and_uid(uid, provider)
    authorizations = where(uid: uid, provider: provider)
    authorizations.first
  end
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :description, :name, :image, :status
  has_many :models
end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :description, :name, :model_id
  belongs_to :model
end

app/models/car_user.rb
class CarUser < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :tooltip, :status, :image_url, :cant_articles, :path, :small_description

  has_many :articles

  # bd methods
  def self.get_active_categories()
    categories = find(:all, :select => 'c.id, c.name, c.tooltip, c.image_url, c.path, count(a.id) as cant_articles',
                     :from   => 'categories c',
                     :joins  => 'left join articles a on c.id = a.id',
                     :group  => 'c.id, c.name, c.tooltip, c.image_url, c.path',
                     :order  => 'c.name asc',
		     :conditions => "status = 'A'") 

    return categories
  end

  def self.get_category_by_path(path_filter)
    categories = where(path: path_filter)
    return categories[0] if categories.any?
  end
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :messages
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :email, :name, :website, :photo_url, :article_id

  belongs_to :article
  belongs_to :demo
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :chat_id, :description, :user_id

  belongs_to :user
  belongs_to :chat
end

app/models/model.rb
class Model < ActiveRecord::Base
  attr_accessible :brand_id, :description, :name
  belongs_to :brand
  has_many :cars
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :ip, :rate
end

app/models/social_user.rb
class SocialUser

  attr_accessor :uid, :name, :email, :photo_url

  def initialize uid, name, email, photo_url
    @uid = uid
    @name = name
    @email = email
    @photo_url = photo_url
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :nickname, :password, :webpage

  has_many :messages

  def self.get_or_set_user(user_id)
    logger.debug 'user_id es: ' 
    logger.debug user_id

    if user_id.nil?
      user = self.new
      user.nickname = "user_" + Time.now.to_i.to_s
      if user.save
        user_id = user.id
      end
    else
      user = self.find(user_id)
    end

    # Return the user
    user
    
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlos Duclos - Game Developer</title>
  <%=csrf_meta_tags %>

  <%= stylesheet_link_tag "highlight/styles/default", :title => 'Default' %>
  <%= stylesheet_link_tag "styles-main" %>
  <%= stylesheet_link_tag "navigation" %>
  <%= stylesheet_link_tag "article" %>
  <%= stylesheet_link_tag "dashboard" %>
  <%= stylesheet_link_tag "comment" %>
  <%= stylesheet_link_tag "rightmenu" %>
  <%= stylesheet_link_tag "socialnetworks" %>
  <%= stylesheet_link_tag "bootstrap/css/bootstrap" %>
  <%= stylesheet_link_tag "jquery/jRating.jquery" %>
  <%= stylesheet_link_tag "jquery/ui.notify" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "highlight/highlight.pack" %>
  <%= javascript_include_tag "jquery/jquery-ui-1.8.22.custom.min" %>
  <%= javascript_include_tag "jquery/jqFloat" %>
  <%= javascript_include_tag "jquery/jRating.jquery" %>
  <%= javascript_include_tag "jquery/ui.notify" %>
  
  <%= javascript_include_tag "bootstrap/js/bootstrap" %>
  <%= javascript_include_tag "chat.pusher.events" %>
  <%= javascript_include_tag "chat.functions" %>
  <%= javascript_include_tag "navigation" %>
  <%= javascript_include_tag "dashboard" %>
  <%= javascript_include_tag "facebook.api" %>
  <%= javascript_include_tag "header" %>
  <%= javascript_include_tag "article" %>
  <%= javascript_include_tag "comment" %>
  

  <meta property="og:title" content="Carlos21 Great Tutorials!" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://www.carlos21.com" />
  <meta property="og:image" content="http://www.carlos21.com/assets/yope.jpg" />
  <meta property="og:site_name" content="Carlos21" />
  <meta property="fb:app_id" content="467557929946955" />

  <script type="text/javascript" >
    hljs.tabReplace = ' ';
    hljs.initHighlightingOnLoad();
    
    PUSHER_KEY = '<%= Pusher.key %>';
    post_message_url = "<%=post_message_url%>";
    typing_status_url = "<%=typing_status_url%>";
    change_nickname_url = "<%=change_nickname_url%>";
    post_message_url = "<%=post_message_url%>";
    authorization_uid = "<%= session[:uid] %>";
    socialnetworks_url = "<%= socialnetworks_url %>";
    create_comment_url = "<%= create_comment_url %>";
  </script>

  <script type="text/javascript">
    $(document).ready(function(){
      // simple jRating call
      $('.basic').jRating({
        length : 5,
        decimalLength : 5
      });

      <% if session[:show_rating] == true %>
          setTimeout(function(){
            if ($(".rating")) {
              $(".rating").slideDown('slow');  
            }
          }, 2000);
      <% end %>

    });
  </script>

  <%= yield :head %>

</head>
<body>
  
  <!-- HEADER -->
  <%= render 'partials/header' %>
  
  <div class="maincontent">
    
    <!-- NAVIGATION -->
    <%= render 'partials/navigation' %>
    
    <!-- CONTENT -->
    <div class="content">
      <div class="section-content">

        <!-- PAGES PATH -->
        <%= render 'partials/pages_path', :locals => {:pages_path => @pages_path} %>

        <!-- MAIN CONTENT -->
        <%= yield %>

      </div>
    </div>  

  </div>

  <!-- FOOTER -->
  <%= render 'partials/footer' %>

  <!-- RATING -->
  <%= render 'partials/rating' %>

  

</body>
</html>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="footer-item">
      <span><%= t(:contact_me_label) %></span>
      <ul>
        <li><%= link_to 'Twitter', 'https://twitter.com/DarkZeratul64', :target => '_blank' %></li>
        <li><%= link_to 'LinkedIn', 'http://pe.linkedin.com/pub/carlos-duclos-caballero/20/aa5/5b1', :target => '_blank' %></li>
        <li><%= mail_to "darkzeratul64@gmail.com", 'Gmail' %></li>
        <li><%= mail_to 'dark_zeratul64@hotmail.com', 'Hotmail' %></li>
        <li><%= link_to 'Github', 'https://github.com/carlos21', :target => '_blank' %></li>
        <li><%= link_to 'Gittip', 'https://www.gittip.com/carlos21', :target => '_blank' %></li>
      </ul>
    </div>
    <div class="footer-item">
      <span><%= t(:interests_label) %></span>
      <ul>
        <li><%= link_to 'Ruby', 'http://www.ruby-lang.org/es', :target => '_blank' %></li>
        <li><%= link_to 'Rails', 'http://rubyonrails.org/', :target => '_blank' %></li>
        <li><%= link_to 'Css3', 'http://www.css3.info/', :target => '_blank' %></li>
        <li><%= link_to 'Html5', 'http://html5.org/', :target => '_blank' %></li>
        <li><%= link_to 'JQuery', 'http://jquery.com/', :target => '_blank' %></li>
        <li><%= link_to 'Linux', 'http://www.linux.org/', :target => '_blank' %></li>
      </ul>
    </div>
    <div class="footer-item">
      <span><%= t(:about_me_label) %></span>
      <ul>
        <li>
          <%= link_to t(:view_profile_label), (root_url + @locale.to_s + '/about-me') %>
        </li>
      </ul>
    </div>
    <div class="footer-item">
      <span><%= t(:home_label) %></span>
      <ul>
        <li>
          <%= link_to t(:go_label), root_path %>
        </li>
      </ul>
    </div>
    
    
    
  </div>

  
  
</div>

app/views/partials/_header.html.erb
<div class="header">
  <div class="header-top1">
    
    <!-- TOP BAR -->    
    <%= render 'partials/nav_top_bar' %>
    
  </div>

  <div class="header-top2">

    <!-- PHOTO -->
    <div class="photo">
      <%= image_tag 'yope.jpg', :size => '60x60' %>
    </div>

    <!-- DESCRIPTION -->
    <div class="details">
      <h1>Carlos Duclós</h1>
      <ul>
        <li>&nbsp;Game Developer</li>
        <li>&nbsp;Web & Mobile</li>
      </ul>
    </div>

    <div class="header-right-buttons">
      
      <% if request.fullpath == "/" %>
        <%= render :partial => 'socialnetworks/facebook_button', :locals => {:url => 'http://carlos21.com'} %>
        <%= render :partial => 'socialnetworks/twitter_button', :locals => {:url => 'http://carlos21.com'} %>
        <%# render :partial => 'socialnetworks/googleplus_button', :locals => {:url => 'http://carlos21.com'} %>
      <% end %>
    </div>

    <!-- CHAT -->
    <%= render 'chat/chat' %>

  </div>

</div>

app/views/partials/_nav_top_bar.html.erb
<div id="navbar-example" class="navbar navbar-static" style="border-radius: 0px;">
  <div class="navbar-inner" style="border-radius: 0px;">
    <div class="container" style="width: auto;">

      <%= link_to t(:welcometo_label) + " carlos21.com - Great tutorials", root_path, :class => 'brand' %> 

      <ul class="nav" role="navigation" style="float:right">
        <li class="active"><%= link_to t(:home_label), root_path %> </li>
        <li><%= link_to t(:about_me_label), (root_url + @locale + '/about-me') %></li>
        
         <!-- INTERESTS -->
        <li class="dropdown">
          <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
            <%= t(:interests_label) %> 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
            <li><%= link_to 'Ruby', 'http://www.ruby-lang.org/es', :target => '_blank' %></li>
            <li><%= link_to 'Rails', 'http://rubyonrails.org/', :target => '_blank' %></li>
            <li><%= link_to 'Css3', 'http://www.css3.info/', :target => '_blank' %></li>
            <li><%= link_to 'Html5', 'http://html5.org/', :target => '_blank' %></li>
            <li><%= link_to 'JQuery', 'http://jquery.com/', :target => '_blank' %></li>
            <li><%= link_to 'Linux', 'http://www.linux.org/', :target => '_blank' %></li>
          </ul>
        </li>

        <!-- CONTACT ME -->
        <li class="dropdown">
          <a id="drop2" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
            <%= t(:contact_me_label) %> 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
            <li><%= link_to 'Twitter', 'https://twitter.com/DarkZeratul64', :target => '_blank' %></li>
            <li><%= link_to 'LinkedIn', 'http://pe.linkedin.com/pub/carlos-duclos-caballero/20/aa5/5b1', :target => '_blank' %></li>
            <li><%= mail_to "darkzeratul64@gmail.com", 'Gmail' %></li>
            <li><%= mail_to 'dark_zeratul64@hotmail.com', 'Hotmail' %></li>
            <li><%= link_to 'Github', 'https://github.com/carlos21', :target => '_blank' %></li>
            <li><%= link_to 'Gittip', 'https://www.gittip.com/carlos21', :target => '_blank' %></li>
          </ul>
        </li>

        <!-- DEMOS -->
        <li class="dropdown">
          <a id="drop3" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
            Demos
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
            <% @article_demos.each do |d| %>
            <li><%= link_to d.name, demo_content_path(@locale, d.path)  %></li>
            <% end %>
          </ul>
        </li>

        <!-- LANGUAGE -->
        <li class="dropdown">
          <a id="drop4" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
            <% if @locale == Constants::LANG_ENGLISH %>
              <%= t(:english_label) %>
            <% else %>
              <%= t(:spanish_label) %>
            <% end %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="drop4">
            <li>
              <% if @locale == Constants::LANG_ENGLISH %>
                <% lang = t(:spanish_label); locale = Constants::LANG_SPANISH  %>
              <% else %>
                <% lang = t(:english_label); locale = Constants::LANG_ENGLISH  %>
              <% end %>
              <%= link_to lang, change_language_path(locale) %>
            </li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/partials/_navigation.html.erb
<div class="navigation">
  <h1><%= t(:topics_label) %></h1>
  <% class_name = '' %>
  <% @categories.each do |c| %>
    <% if @category_selected.path == c.path then class_name = 'selected-name' else class_name = 'name' end %>
    <%= link_to guides_path(@locale, c.path) do %>
      <div class="<%= class_name %>" data-placement="right" data-original-title="<%= c.tooltip %>">
        <%= c.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/partials/_pages_path.html.erb
<% if !@pages_path.nil? %>
  <% if @pages_path.size > 1 %>
    <div class="pages-path">
      <% count = 0 %>
      <% @pages_path.each do |page| %>
        <div class="pages-path-item">
          <% if count == 0 %>
            &nbsp;&nbsp;<%= link_to page[0], root_path  %> 
          <% elsif count == @pages_path.size - 1 %>
            <%= page[0] %>
          <% else %>
            <%= link_to page[0], guides_path(@locale, page[1]) %>
          <% end %>
        </div>

        <% if count != @pages_path.size - 1 %>
          <div class="pages-path-item" style="padding-top: 6px; height: 16px">
            <i class="icon-chevron-right"></i>
          </div>
        <% end %>
        
      <% count += 1 %>
      <% end %>
      
      
    </div>
  <% end %>  
<% end %>

app/views/partials/_rating.html.erb
<script type="text/javascript">
  function closeRatingNotification() {
    $(".rating").slideUp();
  }
</script>

<div class="rating">
  <div class="rating-header">
    <button type="button" class="close" style="color:white" data-dismiss="alert" onclick="closeRatingNotification();">×</button>
  </div>
  <div class="rating-content">
    <div class="rating-container">
      <div class="rating-name">
        <%=t(:how_much_did_you_like_the_page_label) %>
      </div>
      <div class="rating-stars">
        <div class="basic" id="20_1"></div>
      </div>
      <div class="rating-thanks">
        <%=t(:thanks_rating) %>
      </div>
    </div>
  </div>
  
  
</div>

app/views/partials/_rightmenu.html.erb
<div class="rightmenu">
  <h1><%= t(:all_demos_label) %></h1>
  <% @demos.each do |d| %>
  
    <a href="<%= d.url %>" target="_blank">
      <div class="name">
        <%= d.name %>
      </div>
    </a>
  <% end %>
</div>

app/views/socialnetworks/_ask_for_login.html.erb
<!-- ASK TO LOGIN -->
<h3 id="ask_for_login"><%= @form_title || t(:ask_for_login_label) %></h3>
<div class="socialnetworks-litle">
  <div>
    <%= link_to root_url + Constants::FACEBOOK_LOGIN_URL do %>
      <%= image_tag 'facebook.jpg', :size => '50x50' %>
    <% end %>
  </div>
  <div>
    <%= link_to root_url + Constants::TWITTER_LOGIN_URL do %>
      <%= image_tag 'twitter.jpg', :size => '50x50' %>
    <% end %>
  </div>
  <div>
    <%= link_to root_url + Constants::GITHUB_LOGIN_URL do %>
      <%= image_tag 'github.jpg', :size => '50x50' %>
    <% end %>
  </div>
</div>

app/views/socialnetworks/_facebook_button.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=467557929946955";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="facebook-button">
  <div class="fb-like" data-href="<%= url %>" data-send="false" data-layout="box_count" data-width="66" data-show-faces="false"></div>  
</div>

app/views/socialnetworks/_googleplus_button.html.erb
<div class="googleplus-button">
  <g:plusone href="<%= url %>"></g:plusone>
</div>

<script type="text/javascript">
  window.___gcfg = {
    lang: 'es'
  };

  (function() {
    var po = document.createElement('script'); 
    po.type = 'text/javascript'; 
    po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; 
    s.parentNode.insertBefore(po, s);
  })();
</script>

app/views/socialnetworks/_popup.html.erb
<div id="socialnetworks">
  <div>
    <%= link_to root_url + Constants::FACEBOOK_LOGIN_URL do %>
      <%= image_tag 'facebook.jpg', :size => '100x100' %>
    <% end %>
  </div>
  <div>
    <%= link_to root_url + Constants::TWITTER_LOGIN_URL do %>
      <%= image_tag 'twitter.jpg', :size => '100x100' %>
    <% end %>
  </div>
  <div>
    <%= link_to root_url + Constants::GITHUB_LOGIN_URL do %>
      <%= image_tag 'github.jpg', :size => '100x100' %>
    <% end %>
  </div>
</div>

app/views/socialnetworks/_twitter_button.html.erb
<div class="twitter-button">
  <a href="http://carlos21.com" class="twitter-share-button" data-url="<%= url %>" data-lang="en" data-related="anywhereTheJavascriptAPI" data-count="vertical">Tweet</a>
</div>

<script>
  !function(d,s,id){
    var js,fjs = d.getElementsByTagName(s)[0];
    if(!d.getElementById(id)){
      js=d.createElement(s);
      js.id=id;
      js.src="https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js,fjs);
    }
  }(document,"script","twitter-wjs");
</script>